# _config.yml
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
mathjax: true
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

defaults:
    values:
      mathjax: true
